/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Appointment {
  'id' : bigint,
  'status' : AppointmentStatus,
  'bookedBy' : Principal,
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'preferredDate' : bigint,
  'serviceId' : bigint,
  'phone' : string,
}
export type AppointmentStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'confirmed' : null };
export interface CommissionLog {
  'id' : bigint,
  'source' : string,
  'date' : bigint,
  'description' : string,
  'amount' : bigint,
}
export interface News {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'date' : bigint,
  'category' : string,
}
export interface Scheme {
  'id' : bigint,
  'name' : string,
  'officialLink' : string,
  'description' : string,
  'eligibility' : string,
  'documentsRequired' : Array<string>,
  'category' : string,
}
export interface Service {
  'id' : bigint,
  'title' : string,
  'description' : string,
  'iconName' : string,
  'category' : ServiceCategory,
}
export type ServiceCategory = { 'pan' : null } |
  { 'aadhaar' : null } |
  { 'government' : null } |
  { 'digital' : null };
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Wallet {
  'balance' : bigint,
  'totalEarned' : bigint,
  'referralCount' : bigint,
  'totalWithdrawn' : bigint,
}
export interface WithdrawalRequest {
  'id' : bigint,
  'bankAccountNumber' : string,
  'status' : WithdrawalStatus,
  'ifscCode' : string,
  'createdAt' : bigint,
  'user' : Principal,
  'accountHolderName' : string,
  'processedAt' : [] | [bigint],
  'amount' : bigint,
}
export type WithdrawalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addNews' : ActorMethod<[News], bigint>,
  'addScheme' : ActorMethod<[Scheme], bigint>,
  'addService' : ActorMethod<[Service], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bookAppointment' : ActorMethod<[Appointment], bigint>,
  'creditWallet' : ActorMethod<[Principal, bigint], undefined>,
  'deleteNews' : ActorMethod<[bigint], undefined>,
  'deleteScheme' : ActorMethod<[bigint], undefined>,
  'deleteService' : ActorMethod<[bigint], undefined>,
  'getAllAppointments' : ActorMethod<[], Array<Appointment>>,
  'getAllCommissionLogs' : ActorMethod<[], Array<CommissionLog>>,
  'getAllNews' : ActorMethod<[], Array<News>>,
  'getAllSchemes' : ActorMethod<[], Array<Scheme>>,
  'getAllServices' : ActorMethod<[], Array<Service>>,
  'getAllWallets' : ActorMethod<[], Array<Wallet>>,
  'getAllWithdrawalRequests' : ActorMethod<[], Array<WithdrawalRequest>>,
  'getAppointment' : ActorMethod<[bigint], Appointment>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyWithdrawalRequests' : ActorMethod<[], Array<WithdrawalRequest>>,
  'getTotalCommission' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWallet' : ActorMethod<[], Wallet>,
  'getWithdrawalRequest' : ActorMethod<[bigint], WithdrawalRequest>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logCommission' : ActorMethod<[bigint, string, string], bigint>,
  'registerReferral' : ActorMethod<[string], undefined>,
  'registerWithReferralCode' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedInitialData' : ActorMethod<[], undefined>,
  'submitWithdrawalRequest' : ActorMethod<
    [bigint, string, string, string],
    bigint
  >,
  'updateAppointmentStatus' : ActorMethod<
    [bigint, AppointmentStatus],
    undefined
  >,
  'updateNews' : ActorMethod<[bigint, News], undefined>,
  'updateScheme' : ActorMethod<[bigint, Scheme], undefined>,
  'updateService' : ActorMethod<[bigint, Service], undefined>,
  'updateWithdrawalRequest' : ActorMethod<
    [bigint, WithdrawalStatus],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];