/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const News = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'date' : IDL.Int,
  'category' : IDL.Text,
});
export const Scheme = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'officialLink' : IDL.Text,
  'description' : IDL.Text,
  'eligibility' : IDL.Text,
  'documentsRequired' : IDL.Vec(IDL.Text),
  'category' : IDL.Text,
});
export const ServiceCategory = IDL.Variant({
  'pan' : IDL.Null,
  'aadhaar' : IDL.Null,
  'government' : IDL.Null,
  'digital' : IDL.Null,
});
export const Service = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'iconName' : IDL.Text,
  'category' : ServiceCategory,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AppointmentStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Appointment = IDL.Record({
  'id' : IDL.Nat,
  'status' : AppointmentStatus,
  'bookedBy' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'preferredDate' : IDL.Int,
  'serviceId' : IDL.Nat,
  'phone' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addNews' : IDL.Func([News], [IDL.Int], []),
  'addScheme' : IDL.Func([Scheme], [IDL.Int], []),
  'addService' : IDL.Func([Service], [IDL.Int], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bookAppointment' : IDL.Func([Appointment], [IDL.Int], []),
  'deleteNews' : IDL.Func([IDL.Nat], [], []),
  'deleteScheme' : IDL.Func([IDL.Nat], [], []),
  'deleteService' : IDL.Func([IDL.Nat], [], []),
  'getAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'getAllNews' : IDL.Func([], [IDL.Vec(News)], ['query']),
  'getAllSchemes' : IDL.Func([], [IDL.Vec(Scheme)], ['query']),
  'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getAppointment' : IDL.Func([IDL.Nat], [Appointment], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedInitialData' : IDL.Func([], [], []),
  'updateAppointmentStatus' : IDL.Func([IDL.Nat, AppointmentStatus], [], []),
  'updateNews' : IDL.Func([IDL.Nat, News], [], []),
  'updateScheme' : IDL.Func([IDL.Nat, Scheme], [], []),
  'updateService' : IDL.Func([IDL.Nat, Service], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const News = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'date' : IDL.Int,
    'category' : IDL.Text,
  });
  const Scheme = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'officialLink' : IDL.Text,
    'description' : IDL.Text,
    'eligibility' : IDL.Text,
    'documentsRequired' : IDL.Vec(IDL.Text),
    'category' : IDL.Text,
  });
  const ServiceCategory = IDL.Variant({
    'pan' : IDL.Null,
    'aadhaar' : IDL.Null,
    'government' : IDL.Null,
    'digital' : IDL.Null,
  });
  const Service = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'iconName' : IDL.Text,
    'category' : ServiceCategory,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AppointmentStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Appointment = IDL.Record({
    'id' : IDL.Nat,
    'status' : AppointmentStatus,
    'bookedBy' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'preferredDate' : IDL.Int,
    'serviceId' : IDL.Nat,
    'phone' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addNews' : IDL.Func([News], [IDL.Int], []),
    'addScheme' : IDL.Func([Scheme], [IDL.Int], []),
    'addService' : IDL.Func([Service], [IDL.Int], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bookAppointment' : IDL.Func([Appointment], [IDL.Int], []),
    'deleteNews' : IDL.Func([IDL.Nat], [], []),
    'deleteScheme' : IDL.Func([IDL.Nat], [], []),
    'deleteService' : IDL.Func([IDL.Nat], [], []),
    'getAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'getAllNews' : IDL.Func([], [IDL.Vec(News)], ['query']),
    'getAllSchemes' : IDL.Func([], [IDL.Vec(Scheme)], ['query']),
    'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getAppointment' : IDL.Func([IDL.Nat], [Appointment], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedInitialData' : IDL.Func([], [], []),
    'updateAppointmentStatus' : IDL.Func([IDL.Nat, AppointmentStatus], [], []),
    'updateNews' : IDL.Func([IDL.Nat, News], [], []),
    'updateScheme' : IDL.Func([IDL.Nat, Scheme], [], []),
    'updateService' : IDL.Func([IDL.Nat, Service], [], []),
  });
};

export const init = ({ IDL }) => { return []; };