/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const News = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'date' : IDL.Int,
  'category' : IDL.Text,
});
export const Scheme = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'officialLink' : IDL.Text,
  'description' : IDL.Text,
  'eligibility' : IDL.Text,
  'documentsRequired' : IDL.Vec(IDL.Text),
  'category' : IDL.Text,
});
export const ServiceCategory = IDL.Variant({
  'pan' : IDL.Null,
  'aadhaar' : IDL.Null,
  'government' : IDL.Null,
  'digital' : IDL.Null,
});
export const Service = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'iconName' : IDL.Text,
  'category' : ServiceCategory,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AppointmentStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Appointment = IDL.Record({
  'id' : IDL.Nat,
  'status' : AppointmentStatus,
  'bookedBy' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'preferredDate' : IDL.Int,
  'serviceId' : IDL.Nat,
  'phone' : IDL.Text,
});
export const CommissionLog = IDL.Record({
  'id' : IDL.Nat,
  'source' : IDL.Text,
  'date' : IDL.Int,
  'description' : IDL.Text,
  'amount' : IDL.Nat,
});
export const LeadSubmission = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'rewardCredited' : IDL.Bool,
  'email' : IDL.Text,
  'serviceInterest' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});
export const CustomerMessage = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'repliedAt' : IDL.Opt(IDL.Int),
  'message' : IDL.Text,
  'senderName' : IDL.Text,
  'phone' : IDL.Text,
  'reply' : IDL.Opt(IDL.Text),
});
export const CustomerReview = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : IDL.Int,
  'authorName' : IDL.Text,
  'reviewText' : IDL.Text,
  'approved' : IDL.Bool,
  'rating' : IDL.Nat,
});
export const Wallet = IDL.Record({
  'balance' : IDL.Nat,
  'totalEarned' : IDL.Nat,
  'referralCount' : IDL.Nat,
  'totalWithdrawn' : IDL.Nat,
});
export const WithdrawalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const WithdrawalRequest = IDL.Record({
  'id' : IDL.Nat,
  'bankAccountNumber' : IDL.Text,
  'status' : WithdrawalStatus,
  'ifscCode' : IDL.Text,
  'createdAt' : IDL.Int,
  'user' : IDL.Principal,
  'accountHolderName' : IDL.Text,
  'processedAt' : IDL.Opt(IDL.Int),
  'amount' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addNews' : IDL.Func([News], [IDL.Int], []),
  'addScheme' : IDL.Func([Scheme], [IDL.Int], []),
  'addService' : IDL.Func([Service], [IDL.Int], []),
  'approveReview' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bookAppointment' : IDL.Func([Appointment], [IDL.Int], []),
  'creditWallet' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'deleteNews' : IDL.Func([IDL.Nat], [], []),
  'deleteScheme' : IDL.Func([IDL.Nat], [], []),
  'deleteService' : IDL.Func([IDL.Nat], [], []),
  'getAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'getAllCommissionLogs' : IDL.Func([], [IDL.Vec(CommissionLog)], ['query']),
  'getAllLeadSubmissions' : IDL.Func([], [IDL.Vec(LeadSubmission)], ['query']),
  'getAllMessages' : IDL.Func([], [IDL.Vec(CustomerMessage)], ['query']),
  'getAllNews' : IDL.Func([], [IDL.Vec(News)], ['query']),
  'getAllReviews' : IDL.Func([], [IDL.Vec(CustomerReview)], ['query']),
  'getAllSchemes' : IDL.Func([], [IDL.Vec(Scheme)], ['query']),
  'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getAllWallets' : IDL.Func([], [IDL.Vec(Wallet)], ['query']),
  'getAllWithdrawalRequests' : IDL.Func(
      [],
      [IDL.Vec(WithdrawalRequest)],
      ['query'],
    ),
  'getAppointment' : IDL.Func([IDL.Nat], [Appointment], ['query']),
  'getApprovedReviews' : IDL.Func([], [IDL.Vec(CustomerReview)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyWithdrawalRequests' : IDL.Func(
      [],
      [IDL.Vec(WithdrawalRequest)],
      ['query'],
    ),
  'getTotalCommission' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWallet' : IDL.Func([], [Wallet], ['query']),
  'getWithdrawalRequest' : IDL.Func([IDL.Nat], [WithdrawalRequest], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logCommission' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Int], []),
  'markLeadRewarded' : IDL.Func([IDL.Nat], [], []),
  'registerReferral' : IDL.Func([IDL.Text], [], []),
  'registerWithReferralCode' : IDL.Func([IDL.Text], [], []),
  'replyToMessage' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedInitialData' : IDL.Func([], [], []),
  'submitLead' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'submitMessage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'submitReview' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [IDL.Nat], []),
  'submitWithdrawalRequest' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Int],
      [],
    ),
  'updateAppointmentStatus' : IDL.Func([IDL.Nat, AppointmentStatus], [], []),
  'updateNews' : IDL.Func([IDL.Nat, News], [], []),
  'updateScheme' : IDL.Func([IDL.Nat, Scheme], [], []),
  'updateService' : IDL.Func([IDL.Nat, Service], [], []),
  'updateWithdrawalRequest' : IDL.Func([IDL.Nat, WithdrawalStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const News = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'date' : IDL.Int,
    'category' : IDL.Text,
  });
  const Scheme = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'officialLink' : IDL.Text,
    'description' : IDL.Text,
    'eligibility' : IDL.Text,
    'documentsRequired' : IDL.Vec(IDL.Text),
    'category' : IDL.Text,
  });
  const ServiceCategory = IDL.Variant({
    'pan' : IDL.Null,
    'aadhaar' : IDL.Null,
    'government' : IDL.Null,
    'digital' : IDL.Null,
  });
  const Service = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'iconName' : IDL.Text,
    'category' : ServiceCategory,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AppointmentStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Appointment = IDL.Record({
    'id' : IDL.Nat,
    'status' : AppointmentStatus,
    'bookedBy' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'preferredDate' : IDL.Int,
    'serviceId' : IDL.Nat,
    'phone' : IDL.Text,
  });
  const CommissionLog = IDL.Record({
    'id' : IDL.Nat,
    'source' : IDL.Text,
    'date' : IDL.Int,
    'description' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const LeadSubmission = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'rewardCredited' : IDL.Bool,
    'email' : IDL.Text,
    'serviceInterest' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const CustomerMessage = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'repliedAt' : IDL.Opt(IDL.Int),
    'message' : IDL.Text,
    'senderName' : IDL.Text,
    'phone' : IDL.Text,
    'reply' : IDL.Opt(IDL.Text),
  });
  const CustomerReview = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : IDL.Int,
    'authorName' : IDL.Text,
    'reviewText' : IDL.Text,
    'approved' : IDL.Bool,
    'rating' : IDL.Nat,
  });
  const Wallet = IDL.Record({
    'balance' : IDL.Nat,
    'totalEarned' : IDL.Nat,
    'referralCount' : IDL.Nat,
    'totalWithdrawn' : IDL.Nat,
  });
  const WithdrawalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const WithdrawalRequest = IDL.Record({
    'id' : IDL.Nat,
    'bankAccountNumber' : IDL.Text,
    'status' : WithdrawalStatus,
    'ifscCode' : IDL.Text,
    'createdAt' : IDL.Int,
    'user' : IDL.Principal,
    'accountHolderName' : IDL.Text,
    'processedAt' : IDL.Opt(IDL.Int),
    'amount' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addNews' : IDL.Func([News], [IDL.Int], []),
    'addScheme' : IDL.Func([Scheme], [IDL.Int], []),
    'addService' : IDL.Func([Service], [IDL.Int], []),
    'approveReview' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bookAppointment' : IDL.Func([Appointment], [IDL.Int], []),
    'creditWallet' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'deleteNews' : IDL.Func([IDL.Nat], [], []),
    'deleteScheme' : IDL.Func([IDL.Nat], [], []),
    'deleteService' : IDL.Func([IDL.Nat], [], []),
    'getAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'getAllCommissionLogs' : IDL.Func([], [IDL.Vec(CommissionLog)], ['query']),
    'getAllLeadSubmissions' : IDL.Func(
        [],
        [IDL.Vec(LeadSubmission)],
        ['query'],
      ),
    'getAllMessages' : IDL.Func([], [IDL.Vec(CustomerMessage)], ['query']),
    'getAllNews' : IDL.Func([], [IDL.Vec(News)], ['query']),
    'getAllReviews' : IDL.Func([], [IDL.Vec(CustomerReview)], ['query']),
    'getAllSchemes' : IDL.Func([], [IDL.Vec(Scheme)], ['query']),
    'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getAllWallets' : IDL.Func([], [IDL.Vec(Wallet)], ['query']),
    'getAllWithdrawalRequests' : IDL.Func(
        [],
        [IDL.Vec(WithdrawalRequest)],
        ['query'],
      ),
    'getAppointment' : IDL.Func([IDL.Nat], [Appointment], ['query']),
    'getApprovedReviews' : IDL.Func([], [IDL.Vec(CustomerReview)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyWithdrawalRequests' : IDL.Func(
        [],
        [IDL.Vec(WithdrawalRequest)],
        ['query'],
      ),
    'getTotalCommission' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWallet' : IDL.Func([], [Wallet], ['query']),
    'getWithdrawalRequest' : IDL.Func(
        [IDL.Nat],
        [WithdrawalRequest],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logCommission' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Int], []),
    'markLeadRewarded' : IDL.Func([IDL.Nat], [], []),
    'registerReferral' : IDL.Func([IDL.Text], [], []),
    'registerWithReferralCode' : IDL.Func([IDL.Text], [], []),
    'replyToMessage' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedInitialData' : IDL.Func([], [], []),
    'submitLead' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'submitMessage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'submitReview' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [IDL.Nat], []),
    'submitWithdrawalRequest' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Int],
        [],
      ),
    'updateAppointmentStatus' : IDL.Func([IDL.Nat, AppointmentStatus], [], []),
    'updateNews' : IDL.Func([IDL.Nat, News], [], []),
    'updateScheme' : IDL.Func([IDL.Nat, Scheme], [], []),
    'updateService' : IDL.Func([IDL.Nat, Service], [], []),
    'updateWithdrawalRequest' : IDL.Func([IDL.Nat, WithdrawalStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };