/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Appointment {
  'id' : bigint,
  'status' : AppointmentStatus,
  'bookedBy' : Principal,
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'preferredDate' : bigint,
  'serviceId' : bigint,
  'phone' : string,
}
export type AppointmentStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'confirmed' : null };
export interface News {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'date' : bigint,
  'category' : string,
}
export interface Scheme {
  'id' : bigint,
  'name' : string,
  'officialLink' : string,
  'description' : string,
  'eligibility' : string,
  'documentsRequired' : Array<string>,
  'category' : string,
}
export interface Service {
  'id' : bigint,
  'title' : string,
  'description' : string,
  'iconName' : string,
  'category' : ServiceCategory,
}
export type ServiceCategory = { 'pan' : null } |
  { 'aadhaar' : null } |
  { 'government' : null } |
  { 'digital' : null };
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addNews' : ActorMethod<[News], bigint>,
  'addScheme' : ActorMethod<[Scheme], bigint>,
  'addService' : ActorMethod<[Service], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bookAppointment' : ActorMethod<[Appointment], bigint>,
  'deleteNews' : ActorMethod<[bigint], undefined>,
  'deleteScheme' : ActorMethod<[bigint], undefined>,
  'deleteService' : ActorMethod<[bigint], undefined>,
  'getAllAppointments' : ActorMethod<[], Array<Appointment>>,
  'getAllNews' : ActorMethod<[], Array<News>>,
  'getAllSchemes' : ActorMethod<[], Array<Scheme>>,
  'getAllServices' : ActorMethod<[], Array<Service>>,
  'getAppointment' : ActorMethod<[bigint], Appointment>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedInitialData' : ActorMethod<[], undefined>,
  'updateAppointmentStatus' : ActorMethod<
    [bigint, AppointmentStatus],
    undefined
  >,
  'updateNews' : ActorMethod<[bigint, News], undefined>,
  'updateScheme' : ActorMethod<[bigint, Scheme], undefined>,
  'updateService' : ActorMethod<[bigint, Service], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];